openapi: 3.0.3

info:
  title: Awale Arena API
  description: |-
    ...
  contact:
    email: contact@colindeseroux.fr
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1

servers:
  - url: http://localhost:3001
    description: Local server

tags:
  - name: Hello
    description: Hello World!

paths:
  /api/hello:
    get:
      tags:
        - Hello
      summary: Hello World!
      description: Hello World!
      operationId: helloWorld
      responses:
        "200":
          description: Hello World!

  /api/bot:
    post:
      tags:
        - Bot
      summary: Add a new bot
      description: Add a new bot with its file.
      operationId: addBot
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                bot:
                  $ref: "#/components/schemas/RequestBodyBot"
                file:
                  type: string
                  format: binary
                  description: The file to upload
      responses:
        "201":
          description: Bot created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Bot"
        "400":
          description: Bad request
          content:
            text/plain:
              example: BotNameAlreadyExists
        "500":
          description: Internal server error
          content:
            text/plain:
              example: OopsError

components:
  schemas:
    RequestBodyBot:
      type: object
      properties:
        name:
          type: string
          example: Bot Mini-Max
        commitLink:
          type: string
          example: https://github.com/<yourPseudo>/<yourRepo>/commit/<yourCommitHash>
        group:
          type: object
          properties:
            name:
              type: string
              example: GroupName
      required:
        - name
        - group
    Group:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: GroupName
    Bot:
      type: object
      properties:
        id:
          type: integer
          format: int64
        createdAt:
          type: string
          format: date-time
        commitLink:
          type: string
          example: https://github.com/<yourPseudo>/<yourRepo>/commit/<yourCommitHash>
        name:
          type: string
          example: Bot Mini-Max
        group:
          $ref: "#/components/schemas/Group"
        activated:
          type: boolean
    Game:
      type: object
      properties:
        id:
          type: integer
          format: int64
        createdAt:
          type: string
          format: date-time
        bot1:
          $ref: "#/components/schemas/Bot"
        bot2:
          $ref: "#/components/schemas/Bot"
        moves:
          type: array
          items:
            type: string
        winner:
          type: number
          format: int64
